### ISSUE TITLE
ERROR: No matching distribution found for nvidia-tensorrt==8.4.1.5

### ISSUE THREAD

**Issue by swdrsk** [gpastal24/ViTPose-Pytorch#6]
Thank you for nice work.
I found the issue when I try to install required library.

##  Environment
OS: MacOS (Intel CPU)
python: 3.8.10 (on virtualenv)
(also happened with python3.11.0)

##  Script

```
cd ViTPose-Pytorch
pip install -r requirements.txt
```

## Error message
```
enevis/dev/ai/ViTPose/ViTPose-Pytorch  
Collecting ffmpeg-python
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Collecting munkres
  Using cached munkres-1.1.4-py2.py3-none-any.whl (7.0 kB)
Collecting numpy<=1.23.0
  Downloading numpy-1.23.0-cp38-cp38-macosx_10_9_x86_64.whl (18.1 MB)
     |████████████████████████████████| 18.1 MB 730 kB/s 
ERROR: Could not find a version that satisfies the requirement nvidia-tensorrt==8.4.1.5 (from versions: 0.0.1.dev4, 0.0.1.dev5)
ERROR: No matching distribution found for nvidia-tensorrt==8.4.1.5
WARNING: You are using pip version 21.1.1; however, version 23.2.1 is available.
You should consider upgrading via the '/Users/xxx/ViTPose/vitpose-env/bin/python -m pip install --upgrade pip' command.
```
Thank you

**Comment by gpastal24** [comment]
Hello you can try to install nvidia pyindex first, and retry.

`pip install nvidia-pyindex`

Or you can switch out nvidia-tensorrt with tensorrt. for example .

`pip install tensorrt==8.5.1.7`

The thing is that tensorrt works only with nvidia gpus so I don't know if it is supported on your mac machine.

**Comment by swdrsk** [comment]
> The thing is that tensorrt works only with nvidia gpus so I don't know if it is supported on your mac machine.

I see.
That's why pip install failed on my machine :(
