### ISSUE TITLE
2D Keypoints

### ISSUE THREAD

**Issue by wambagilles** [gpastal24/ViTPose-Pytorch#7]
Hello thank you for this amazing work. Please I would like to know if there if a way to generate 2D keypoints intead of 3D ones.

**Comment by gpastal24** [comment]
Hi, you can thank the authors of VitPose for their amazing work, I just made it easier to use (at least for me) :P .

The pts are in y,x,conf format you can just discard the 3rd dimension. Confidence is useful if you want to visualize the points with high certainty (usually over .3 I would say depending on the method).

**Comment by wambagilles** [comment]
Oww nice! thank you for the explanation :)
