### ISSUE TITLE
How to train model on custom dataset 

### ISSUE THREAD

**Issue by Priyanshu-Ganwani09** [gpastal24/ViTPose-Pytorch#8]
How can I train a model on a custom dataset, and what is the optimal image size required for training?
Can you Just define the steps to train models

**Comment by gpastal24** [comment]
Hi sorry for the late reply,

I do not provide training code in this repository. 
I wanted to test VitPose without MMCV and I just released inference code for the models.

You can use the official repository for training, or a generic repo for training 2D pose

**Comment by Priyanshu-Ganwani09** [comment]
thanks  for the query !
